In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
import sys

sys.version
sys.path


['',
 'C:\\Users\\STEVEN\\Anaconda3\\python36.zip',
 'C:\\Users\\STEVEN\\Anaconda3\\DLLs',
 'C:\\Users\\STEVEN\\Anaconda3\\lib',
 'C:\\Users\\STEVEN\\Anaconda3',
 'C:\\Users\\STEVEN\\Anaconda3\\lib\\site-packages',
 'C:\\Users\\STEVEN\\Anaconda3\\lib\\site-packages\\win32',
 'C:\\Users\\STEVEN\\Anaconda3\\lib\\site-packages\\win32\\lib',
 'C:\\Users\\STEVEN\\Anaconda3\\lib\\site-packages\\Pythonwin',
 'C:\\Users\\STEVEN\\Anaconda3\\lib\\site-packages\\IPython\\extensions',
 'C:\\Users\\STEVEN\\.ipython']

In [3]:
# Replace the path with the correct path for your data.
y2015 = pd.read_csv(
    'C:\\Users\\STEVEN\\Documents\\Thinkful\\Files\\Loans\\loans.csv',
    skipinitialspace=True,
    header=1
)

# Note the warning about dtypes.

C:\Users\STEVEN\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2728: DtypeWarning: Columns (0,19,55) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [4]:
y2015.head()

id   member_id  loan_amnt  funded_amnt  funded_amnt_inv        term  \
0  68009401  72868139.0    16000.0      16000.0          16000.0   60 months   
1  68354783  73244544.0     9600.0       9600.0           9600.0   36 months   
2  68466916  73356753.0    25000.0      25000.0          25000.0   36 months   
3  68466961  73356799.0    28000.0      28000.0          28000.0   36 months   
4  68495092  73384866.0     8650.0       8650.0           8650.0   36 months   

  int_rate  installment grade sub_grade            ...              \
0   14.85%       379.39     C        C5            ...               
1    7.49%       298.58     A        A4            ...               
2    7.49%       777.55     A        A4            ...               
3    6.49%       858.05     A        A2            ...               
4   19.89%       320.99     E        E3            ...               

  num_tl_90g_dpd_24m num_tl_op_past_12m pct_tl_nvr_dlq  percent_bc_gt_75  \
0                0.0                2.0           78.9               0.0   
1                0.0                2.0          100.0              66.7   
2                0.0                0.0          100.0              20.0   
3                0.0                0.0           91.7              22.2   
4                0.0               12.0          100.0              50.0   

  pub_rec_bankruptcies tax_liens tot_hi_cred_lim total_bal_ex_mort  \
0                  0.0       2.0        298100.0           31329.0   
1                  0.0       0.0         88635.0           55387.0   
2                  0.0       0.0        373572.0           68056.0   
3                  0.0       0.0        304003.0           74920.0   
4                  1.0       0.0         38998.0           18926.0   

  total_bc_limit total_il_high_credit_limit  
0       281300.0                    13400.0  
1        12500.0                    75635.0  
2        38400.0                    82117.0  
3        41500.0                    42503.0  
4         2750.0                    18248.0  

[5 rows x 111 columns]

In [5]:
categorical = y2015.select_dtypes(include=['object'])
for i in categorical:
    column = categorical[i]
    print(i)
    print(column.nunique())

id
421097
term
2
int_rate
110
grade
7
sub_grade
35
emp_title
120812
emp_length
11
home_ownership
4
verification_status
3
issue_d
12
loan_status
7
pymnt_plan
1
url
421095
desc
34
purpose
14
title
27
zip_code
914
addr_state
49
earliest_cr_line
668
revol_util
1211
initial_list_status
2
last_pymnt_d
25
next_pymnt_d
4
last_credit_pull_d
26
application_type
2
verification_status_joint
3


In [6]:
print(y2015)

                                                      id   member_id  \
0                                               68009401  72868139.0   
1                                               68354783  73244544.0   
2                                               68466916  73356753.0   
3                                               68466961  73356799.0   
4                                               68495092  73384866.0   
5                                               68506798  73396623.0   
6                                               68566886  73456723.0   
7                                               68577849  73467703.0   
8                                               66310712  71035433.0   
9                                               68476807  73366655.0   
10                                              68341763  72928789.0   
11                                              68356421  73246236.0   
12                                              68426545  733163

In [7]:


# Convert ID and Interest Rate to numeric.
y2015['id'] = pd.to_numeric(y2015['id'], errors='coerce')
y2015['int_rate'] = pd.to_numeric(y2015['int_rate'].str.strip('%'), errors='coerce')



In [8]:
# Drop other columns with many unique variables
y2015.drop(['url', 'emp_title', 'zip_code', 'earliest_cr_line', 'revol_util',
            'sub_grade', 'addr_state', 'desc'], 1, inplace=True)

In [9]:
y2015.tail()

id   member_id  loan_amnt  funded_amnt  funded_amnt_inv  \
421092  36271333.0  38982739.0    13000.0      13000.0          13000.0   
421093  36490806.0  39222577.0    12000.0      12000.0          12000.0   
421094  36271262.0  38982659.0    20000.0      20000.0          20000.0   
421095         NaN         NaN        NaN          NaN              NaN   
421096         NaN         NaN        NaN          NaN              NaN   

              term  int_rate  installment grade emp_length  \
421092   60 months     15.99       316.07     D    5 years   
421093   60 months     19.99       317.86     E     1 year   
421094   36 months     11.99       664.20     B  10+ years   
421095         NaN       NaN          NaN   NaN        NaN   
421096         NaN       NaN          NaN   NaN        NaN   

                   ...             num_tl_90g_dpd_24m  num_tl_op_past_12m  \
421092             ...                            0.0                 3.0   
421093             ...                            1.0                 2.0   
421094             ...                            0.0                 1.0   
421095             ...                            NaN                 NaN   
421096             ...                            NaN                 NaN   

       pct_tl_nvr_dlq percent_bc_gt_75 pub_rec_bankruptcies tax_liens  \
421092          100.0             50.0                  1.0       0.0   
421093           95.0             66.7                  0.0       0.0   
421094          100.0             50.0                  0.0       1.0   
421095            NaN              NaN                  NaN       NaN   
421096            NaN              NaN                  NaN       NaN   

       tot_hi_cred_lim total_bal_ex_mort  total_bc_limit  \
421092         51239.0           34178.0         10600.0   
421093         96919.0           58418.0          9700.0   
421094         43740.0           33307.0         41700.0   
421095             NaN               NaN             NaN   
421096             NaN               NaN             NaN   

        total_il_high_credit_limit  
421092                     33239.0  
421093                     69919.0  
421094                         0.0  
421095                         NaN  
421096                         NaN  

[5 rows x 103 columns]

In [10]:
y2015.loan_status.unique()

array(['Current', 'Fully Paid', 'Charged Off', 'Late (31-120 days)',
       'In Grace Period', 'Default', 'Late (16-30 days)', nan],
      dtype=object)

In [11]:
# Remove two summary rows at the end that don't actually contain data.
y2015 = y2015[:-2]

In [26]:
from sklearn import ensemble
from sklearn.model_selection import cross_val_score

rfc = ensemble.RandomForestClassifier()
X = y2015.drop('loan_status', 1)
Y = y2015['loan_status']
X = pd.get_dummies(X)
X = X.dropna(axis=1)

cross_val_score(rfc, X, Y, cv=10)

array([0.97888913, 0.98074137, 0.98150127, 0.9816675 , 0.9764189 ,
       0.97770126, 0.94260134, 0.98078796, 0.97976583, 0.98000285])

In [27]:
corr_matrix = X.corr()

In [28]:
#print(corr_matrix.Current)

In [29]:
#corr_matrix

In [30]:
s_corr = y2015.loan_status.str.get_dummies()
print(s_corr)
Z = y2015 + s_corr

        Charged Off  Current  Default  Fully Paid  In Grace Period  \
0                 0        1        0           0                0   
1                 0        1        0           0                0   
2                 0        0        0           1                0   
3                 0        1        0           0                0   
4                 0        0        0           1                0   
5                 0        1        0           0                0   
6                 0        1        0           0                0   
7                 0        0        0           1                0   
8                 0        1        0           0                0   
9                 0        0        0           1                0   
10                0        1        0           0                0   
11                0        1        0           0                0   
12                0        1        0           0                0   
13                0 

In [31]:
corr_matrix = Z.corr()
corr_matrix2 = y2015.corr()

In [32]:
#print(corr_matrix2)

In [33]:
#print(corr_matrix)

In [34]:
#Changing Loan Status to Categorical Values

def cat_to_num(x):
    if x=='Default':
        return 6
    if x=='Late (31-120 days)':
        return 5
    if x=='Late (16-30 days)':
        return 4
    if x=='In Grace Period':
        return 3
    if x=='Current':
        return 2
    if x=='Fully Paid':
        return 1
    if x=='Charged off':
        return 0

In [35]:
y2015['loan_status_cat'] = y2015['loan_status'].apply(cat_to_num)

In [36]:
#print(y2015['loan_status_cat'])

#still some Nans

In [37]:
corr_matrix2 = y2015.corr()

In [41]:
s = corr_matrix2.loan_status_cat
so = s.sort_values(kind='quicksort')
print(so)

last_pymnt_amnt                  -0.504332
total_rec_prncp                  -0.429093
total_pymnt_inv                  -0.347855
total_pymnt                      -0.347844
mort_acc                         -0.055376
bc_open_to_buy                   -0.052973
avg_cur_bal                      -0.045630
tot_hi_cred_lim                  -0.042213
tot_cur_bal                      -0.039751
total_cu_tl                      -0.037459
num_bc_tl                        -0.030510
total_acc                        -0.030214
total_bc_limit                   -0.029702
mths_since_recent_bc_dlq         -0.026632
num_rev_accts                    -0.026008
mths_since_recent_revol_delinq   -0.025497
mths_since_last_delinq           -0.023293
total_rev_hi_lim                 -0.022886
pct_tl_nvr_dlq                   -0.020022
annual_inc                       -0.018155
mths_since_last_record           -0.015570
max_bal_bc                       -0.014289
mths_since_last_major_derog      -0.013804
pub_rec_ban

In [44]:
F = y2015[['out_prncp', 'out_prncp_inv', 'total_rec_int', 'total_rec_late_fee', 'id', 'member_id', 'bc_util', 'int_rate', 'percent_bc_gt_75', 'all_util', 'num_rev_tl_bal_gt_0', 'dti', 'funded_amnt', 'loan_amnt', 'funded_amnt_inv', 'total_bal_il', 'delinq_2yrs', 'installment']].copy()

In [45]:
F = pd.get_dummies(F)
F = X.dropna(axis=1)

cross_val_score(rfc, F, Y, cv=10)

array([0.97991024, 0.98031393, 0.98159626, 0.98159626, 0.9720019 ,
       0.97857991, 0.84986582, 0.980313  , 0.9793621 , 0.98019285])

In [46]:
#I don't believe it is possible to determine the actual probability of the model to compute with the basic information of payment amount or outstounding amount
# due to the fact that these are so integral in determining the validity of someone's credit.  Also almost all of these are tied in someway to payment amount and outstanding

In [48]:
G = y2015[['out_prncp', 'out_prncp_inv', 'total_rec_int', 'total_rec_late_fee', 'id', 'member_id', 'bc_util', 'int_rate', 'percent_bc_gt_75', 'all_util', 'num_rev_tl_bal_gt_0', 'dti', 'funded_amnt', 'loan_amnt', 'funded_amnt_inv', 'total_bal_il', 'delinq_2yrs', 'installment']].copy()
G = X.dropna(axis=1)
cross_val_score(rfc, G, Y, cv=10)

array([0.97855667, 0.98031393, 0.98114507, 0.98176248, 0.97530278,
       0.97929233, 0.93683061, 0.98059797, 0.9795046 , 0.98073909])